// Generated by CoffeeScript 1.6.1
(function() {
  var Person, PersonView, person, personView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    _this = this;

  Person = (function(_super) {

    __extends(Person, _super);

    function Person() {
      return Person.__super__.constructor.apply(this, arguments);
    }

    Person.prototype.defaults = {
      name: 'John Doe',
      occupation: 'worker'
    };

    return Person;

  })(Backbone.Model);

  PersonView = (function(_super) {

    __extends(PersonView, _super);

    function PersonView() {
      var _this = this;
      this.sayHi = function() {
        return PersonView.prototype.sayHi.apply(_this, arguments);
      };
      return PersonView.__super__.constructor.apply(this, arguments);
    }

    PersonView.prototype.initialize = function() {
      return this.model.on('yay', this.sayHi);
    };

    PersonView.prototype.sayHi = function() {
      return console.log(this);
    };

    return PersonView;

  })(Backbone.View);

  person = new Person;

  personView = new PersonView({
    model: person
  });

  person.trigger('yay');

}).call(this);
